sudo: required

services:
  - docker

before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo service docker restart ; sleep 5 # https://github.com/travis-ci/travis-ci/issues/4778
  - docker-compose up -d
  - docker ps -a

script:
  - docker build -t test demo-apps/bash-batch-job/
  - docker build -t test demo-apps/nodejs-app/