{
 "title": "Docker Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Up Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time{instance=~\"node-exporter:9100\"}"
    }
   ]
  },
  {
   "title": "Node Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{instance=~\"cadvisor:8080\",name=~\".+\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail{instance=~\"node-exporter:9100\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size{instance=~\"node-exporter:9100\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable{instance=~\"node-exporter:9100\"} * 100) / node_memory_MemTotal{instance=~\"node-exporter:9100\"})"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_SwapTotal{instance=~\"node-exporter:9100\"} - node_memory_SwapFree{instance=~\"node-exporter:9100\"}) / (node_memory_SwapTotal{instance=~\"node-exporter:9100\"} )) * 100"
    }
   ]
  },
  {
   "title": "System Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes{instance=~\"node-exporter:9100\"}[$interval]))",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes{instance=~\"node-exporter:9100\"}[$interval]))",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "System Disk I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_bytes_read{instance=~\"node-exporter:9100\"}[$interval]))",
     "legendFormat": "OUT"
    },
    {
     "expr": "- sum(rate(node_disk_bytes_written{instance=~\"node-exporter:9100\"}[$interval]))",
     "legendFormat": "IN"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{instance=~\"node-exporter:9100\",__name__=~\"^node_load.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"cadvisor:8080\",name=~\".+\"}[$interval])) by (image) * 100",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\"cadvisor:8080\",name=~\".+\"}) by (image)",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"cadvisor:8080\",name=~\".+\"}[$interval])) by (image)",
     "legendFormat": "{{ image }}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"cadvisor:8080\",name=~\".+\"}[$interval])) by (image)",
     "legendFormat": "{{image}}"
    }
   ]
  }
 ]
}